### ISSUE TITLE
Tag images on docker hub

### ISSUE THREAD

**Issue by RobbieClarken** [DMSC-Instrument-Data/plankton-misc#6]
Thanks for putting together the extremely helpful `dmscid/epics-gateway` image! I'm starting to use this in a few projects and I'd really like to be able to pin down the version of the image to be pulled from Docker Hub. Currently it is only tagged with `latest` so if you were to update it in the future there is a chance dependent images might break. Would you be able to give it a version tag so users of the image can be sure they will always get the same version?

**Comment by MikeHart85** [comment]
Hi Robbie,

Sorry about the *horribly* late response; somehow I've only just now noticed this.

As you can tell, this isn't a repository we're very active on, and we haven't really touched anything here in a long time. All of our updates have been to the [main repository](https://github.com/DMSC-Instrument-Data/lewis) of the project that uses this as a base image. 

Since we haven't really made use of the docker image much in that project, and tend to just pip install it, we haven't even bothered rebuilding this base image to make sure it is up to date. In fact, it doesn't look like it builds successfully at the moment. I'll have a look at that.

Just in case you are still using it, I've tagged the current `latest` (11 month old) version `v1.0`.
